import RelationsPermissionToRoleCreate from 'components/RelationsPermissionToRole/RelationsPermissionToRoleCreate/RelationsPermissionToRoleCreate';
import RelationsPermissionToRoleEdit from 'components/RelationsPermissionToRole/RelationsPermissionToRoleEdit/RelationsPermissionToRoleEdit';
import RelationsPermissionToRoleList from 'components/RelationsPermissionToRole/RelationsPermissionToRoleList/RelationsPermissionToRoleList';
import RelationsPermissionToRoleShow from 'components/RelationsPermissionToRole/RelationsPermissionToRoleShow/RelationsPermissionToRoleShow';

const relationsPermissionToRole = {
  list: RelationsPermissionToRoleList,
  create: RelationsPermissionToRoleCreate,
  show: RelationsPermissionToRoleShow,
  edit: RelationsPermissionToRoleEdit,
};
export default relationsPermissionToRole;
