query GreWordList(
  $where: GreWordWhereInput
  $skip: Int
  $take: Int
  $orderBy: GreWordOrderByWithRelationInput
) {
  greWords(where: $where, skip: $skip, take: $take, orderBy: $orderBy) {
    id
    spelling
    userId
  }
  total: greWordsCount(where: $where)
}

query GreWordListReferenceUsers($where: UserWhereInput) {
  users(where: $where) {
    id
    email
  }
}
