query GreWordShow($where: GreWordWhereInput) {
  greWord(where: $where) {
    id
    cacheWord {
      text
    }
    gptPrompts {
      id
      cacheResponse {
        text
        cachePrompt {
          text
        }
        cacheWord {
          text
        }
      }
      editedResponse
      greWordId
    }
  }
}
