query UserList(
  $where: UserWhereInput
  $skip: Int
  $take: Int
  $orderBy: UserOrderByWithRelationInput
) {
  users(where: $where, skip: $skip, take: $take, orderBy: $orderBy) {
    id
    email
    meta {
      defaultGreWordSearchPromptInput
      showDefaultGreWordSearchPromptInputs
    }
  }
  total: usersCount(where: $where)
}
