fragment UserFields on User {
  id
  email
  meta {
    defaultGreWordSearchPromptInput
    showDefaultGreWordSearchPromptInputs
  }
}

query users($where: UserWhereInput, $skip: Int, $take: Int) {
  users(where: $where, skip: $skip, take: $take) {
    ...UserFields
  }
  total: usersCount(where: $where)
}
